"""gate_fp32.py: the frozen gate for the fp32-accumulation variant of gemm_q4_kernel_rdna3. G7 only.

DO NOT EDIT THIS FILE. It prints its own md5; the task report must quote it.

  python gate_fp32.py --preflight   instrument check only (no candidate needed). Must pass before any coding.
  python gate_fp32.py               full gate on the candidate in src/q_gemm_rdna3_fp32.cu

Exact reference: random 4-bit weights q, zeros z (true zeros), bf16 scales s and bf16 activations a.
reference = a @ ((q - z) * s), computed in float64. Every kernel is scored as RMS error against it.

Kernels compared:
  triton     production's triton_w4a16_gemm_kernel, as the compiled graph runs it (BLOCK 128/32/32)
  hip_inst   installed gptq_gemm_rdna3 with use_v2_format=True (true zeros), as the patched brain runs it
  cand       the candidate, built from src/q_gemm_rdna3_fp32.cu with its own namespace

Gates (all numbers fixed in advance, see THRESHOLDS):
  I   instrument: triton and hip_inst near the reference; a wrong-zeros control far from it
  P   precision: cand error <= 1.25 x triton error and <= 0.5 x hip_inst error, every shape, M = 1 and 4
  R   repeatability: cand run-to-run RMS difference <= 0.1 x hip_inst run-to-run difference
  S   speed: cand per-token total over production's 255 calls <= triton total - 8.0 ms (M = 1 and 4)
  N   identity: cand launches its own kernel and returns bf16 of shape [M, N]
Exit code 0 only if every gate passes.
"""
import os, sys, re, json, time, shutil, hashlib, random, statistics
os.environ["ROCR_VISIBLE_DEVICES"] = "GPU-d580007fa41ec467"
os.environ["HIP_VISIBLE_DEVICES"] = "GPU-d580007fa41ec467"
os.environ["CUDA_VISIBLE_DEVICES"] = "GPU-d580007fa41ec467"
os.environ["HF_HUB_OFFLINE"] = "1"
os.environ["VLLM_PLUGINS"] = ""
os.environ["PYTORCH_ROCM_ARCH"] = "gfx1100"

HERE = os.path.dirname(os.path.abspath(__file__))
SELF_MD5 = hashlib.md5(open(os.path.abspath(__file__), "rb").read()).hexdigest()
PREFLIGHT = "--preflight" in sys.argv
OUT = os.path.join(HERE, "gate_preflight.json" if PREFLIGHT else "gate_results.json")
THRESHOLDS = {"I_triton_max": 0.01, "I_hip_max": 0.02, "I_broken_min": 0.10,
              "P_vs_triton": 1.25, "P_vs_hip": 0.5, "R_vs_hip": 0.1, "S_margin_ms": 8.0}
G = 32
SEEDS = (11, 22, 33)
MS = (1, 4)
SHAPES = {"qkv": ((5120, 2048), 16), "o": ((768, 5120), 16), "gate_up": ((5120, 4352), 64),
          "down": ((2176, 5120), 64), "qkvz": ((5120, 2048), 48), "gdn_out": ((768, 5120), 47)}
res = {"gate_md5": SELF_MD5, "mode": "preflight" if PREFLIGHT else "full", "thresholds": THRESHOLDS}
print(f"gate_fp32.py md5 {SELF_MD5}  mode {'PREFLIGHT' if PREFLIGHT else 'FULL'}", flush=True)

def save():
    json.dump(res, open(OUT, "w"), indent=2)

def stop(msg):
    print(f"\nSTOP: {msg}", flush=True)
    res["stopped"] = msg
    save()
    sys.exit(2)

import torch
import triton
from torch.utils.cpp_extension import load, ROCM_HOME
from torch.profiler import profile, ProfilerActivity
from vllm import _custom_ops as ops
from vllm.model_executor.kernels.linear.mixed_precision.triton_w4a16 import triton_w4a16_gemm_kernel
dev = "cuda"

if torch.cuda.device_count() != 1:
    stop(f"{torch.cuda.device_count()} cards visible, expected exactly G7")
if torch.cuda.mem_get_info()[0] / 2**30 < 20:
    stop("G7 is not empty")

# ---------------------------------------------------------------- packing into both layouts from one set of true values
def make_case(K, N, M, seed, wrong_zeros=False):
    g = torch.Generator(device="cpu").manual_seed(seed)
    q = torch.randint(0, 16, (K, N), generator=g, dtype=torch.int32)
    z = torch.randint(0, 16, (K // G, N), generator=g, dtype=torch.int32)
    s = (torch.randn(K // G, N, generator=g) * 0.01).to(torch.bfloat16)
    a = torch.randn(M, K, generator=g).to(torch.bfloat16)
    ref = a.double() @ ((q.double() - z.double().repeat_interleave(G, 0)) * s.double().repeat_interleave(G, 0))
    if wrong_zeros:
        z = (z + 1 + torch.randint(0, 14, z.shape, generator=g, dtype=torch.int32)) % 16
    sh = (torch.arange(8, dtype=torch.int64) * 4)   # int64: 15 << 28 overflows int32
    # zeros [K/G, N/8], N packed sequentially: identical for both kernels
    zp = ((z.view(K // G, N // 8, 8).to(torch.int64) & 0xF) << sh).sum(-1)
    zp = torch.where(zp >= 2**31, zp - 2**32, zp).to(torch.int32)
    # Triton: b_q [K, N/8], N packed sequentially
    tq = ((q.view(K, N // 8, 8).to(torch.int64) & 0xF) << sh).sum(-1)
    tq = torch.where(tq >= 2**31, tq - 2**32, tq).to(torch.int32)
    # HIP: qweight [K/8, N], K packed sequentially, then the same gptq_shuffle production applies
    hq = ((q.view(K // 8, 8, N).to(torch.int64) & 0xF) << sh.view(1, 8, 1)).sum(1)
    hq = torch.where(hq >= 2**31, hq - 2**32, hq).to(torch.int32).to(dev).contiguous()
    gidx = torch.empty(0, device=dev, dtype=torch.int)
    ops.gptq_shuffle(hq, gidx, 4)
    return {"a": a.to(dev), "ref": ref.to(dev), "tri": (tq.to(dev), s.to(dev), zp.to(dev)),
            "hip": (hq, zp.to(dev), s.to(dev), gidx)}

def run_triton(a, w):
    b_q, sc, qz = w
    M, K = a.shape; N = b_q.shape[1] * 8
    c = torch.empty((M, N), dtype=a.dtype, device=a.device)
    triton_w4a16_gemm_kernel[(triton.cdiv(M, 128), triton.cdiv(N, 32))](
        a, b_q, sc, qz, c, M, N, K, a.stride(0), a.stride(1), b_q.stride(0), b_q.stride(1),
        c.stride(0), c.stride(1), group_size=G, HAS_ZP=True, ZP_BIAS=8, BLOCK_M=128, BLOCK_N=32, BLOCK_K=32)
    return c

def run_hip(a, w):
    return ops.gptq_gemm_rdna3(a, w[0], w[1], w[2], w[3], True)

def rms_rel(x, ref):
    d = x.double() - ref
    return (d.pow(2).mean().sqrt() / ref.pow(2).mean().sqrt()).item()

KERNELS = {"triton": (run_triton, "tri"), "hip_inst": (run_hip, "hip")}

# ---------------------------------------------------------------- candidate build (full mode only)
if not PREFLIGHT:
    src = os.path.join(HERE, "src", "q_gemm_rdna3_fp32.cu")
    hdr = os.path.join(HERE, "src", "qdq_4_rdna3.cuh")
    if not os.path.exists(src) or not os.path.exists(hdr):
        stop("candidate source src/q_gemm_rdna3_fp32.cu or header missing")
    tag = "fp32cand"
    d = os.path.join(HERE, "build", tag)
    os.makedirs(d, exist_ok=True)
    if os.path.exists(os.path.join(d, "lock")):
        os.remove(os.path.join(d, "lock"))
    def rename(t):
        t = re.sub(r"\bvllm\b", f"vllmht_{tag}", t)
        t = re.sub(r"\bgptq_gemm_rdna3_wmma\b", f"ht_wmma_{tag}", t)
        return re.sub(r"\bgptq_gemm_rdna3\b", f"ht_gemm_{tag}", t)
    stub = f'''

// ---- appended by gate_fp32.py ----
torch::Tensor ht_wmma_{tag}(torch::Tensor a, torch::Tensor b_q_weight, torch::Tensor b_qzeros,
                            torch::Tensor b_scales, bool use_v2_format) {{
  TORCH_CHECK(false, "wmma path not built in this gate (M must be < 16)");
  return a;
}}
#include <torch/extension.h>
PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {{ m.def("gemm", &ht_gemm_{tag}); }}
'''
    open(os.path.join(d, "q_gemm_rdna3.cu"), "w").write(rename(open(src).read()) + stub)
    open(os.path.join(d, "qdq_4_rdna3.cuh"), "w").write(rename(open(hdr).read()))
    if not shutil.which("ninja") or not os.path.exists(os.path.join(ROCM_HOME or "", "bin", "hipcc")):
        stop("ninja or hipcc missing")
    print(f"[{time.strftime('%H:%M:%S')}] building candidate (about a minute)", flush=True)
    try:
        cand = load(name=f"gq4_{tag}", sources=[os.path.join(d, "q_gemm_rdna3.cu")], build_directory=d,
                    extra_include_paths=[d], extra_cuda_cflags=["-O3", "-DUSE_ROCM"], verbose=False)
    except Exception as exc:
        res["build_error"] = str(exc)[-3000:]
        stop(f"candidate build failed: {type(exc).__name__}. The compiler output is above.")
    KERNELS["cand"] = (lambda a, w: cand.gemm(a, w[0], w[1], w[2], True), "hip")

verdict = {}

# ---------------------------------------------------------------- N: identity (full mode)
if not PREFLIGHT:
    c0 = make_case(5120, 4352, 1, 1)
    try:
        out = KERNELS["cand"][0](c0["a"], c0["hip"]); torch.cuda.synchronize()
        with profile(activities=[ProfilerActivity.CUDA]) as p:
            KERNELS["cand"][0](c0["a"], c0["hip"]); torch.cuda.synchronize()
    except Exception as exc:
        stop(f"candidate failed to run: {type(exc).__name__}: {exc}")
    names = [ev.name for ev in p.events() if ev.device_type == torch.autograd.DeviceType.CUDA]
    own = any("vllmht_fp32cand::" in nm for nm in names)
    ok = own and out.dtype == torch.bfloat16 and tuple(out.shape) == (1, 4352)
    verdict["N"] = ok
    res["N"] = {"kernels": names, "dtype": str(out.dtype), "shape": list(out.shape)}
    print(f"N identity: {'PASS' if ok else 'FAIL'}  own kernel {own}, dtype {out.dtype}, shape {tuple(out.shape)}, "
          f"{len(names)} device kernels per call", flush=True)
    save()

# ---------------------------------------------------------------- I, P, R: accuracy against the exact reference
print(f"\n=== error against the exact float64 reference (RMS relative), {len(SEEDS)} seeds", flush=True)
res["accuracy"] = {}
I_ok = P_ok = R_ok = True
for op, ((K, N), _) in SHAPES.items():
    for M in MS:
        row = {k: [] for k in KERNELS}; row["hip_self"] = []; row["cand_self"] = []; row["broken"] = []
        for sd in SEEDS:
            c = make_case(K, N, M, sd)
            for k, (fn, lay) in KERNELS.items():
                row[k].append(rms_rel(fn(c["a"], c[lay]), c["ref"]))
            h1, h2 = run_hip(c["a"], c["hip"]), run_hip(c["a"], c["hip"])
            row["hip_self"].append(rms_rel(h1, h2.double()))
            if "cand" in KERNELS:
                f = KERNELS["cand"][0]
                row["cand_self"].append(rms_rel(f(c["a"], c["hip"]), f(c["a"], c["hip"]).double()))
            bad = make_case(K, N, M, sd, wrong_zeros=True)
            probe = KERNELS["cand"][0] if "cand" in KERNELS else run_hip
            row["broken"].append(rms_rel(probe(bad["a"], bad["hip"]), c["ref"]))
            torch.cuda.synchronize()
        mx = {k: max(v) for k, v in row.items() if v}
        i_ok = mx["triton"] <= THRESHOLDS["I_triton_max"] and mx["hip_inst"] <= THRESHOLDS["I_hip_max"] \
            and min(row["broken"]) >= THRESHOLDS["I_broken_min"]
        I_ok &= i_ok
        line = f"{op:8s} M{M}  triton {mx['triton']:.5f}  hip_inst {mx['hip_inst']:.5f}  broken {min(row['broken']):.3f}"
        if "cand" in KERNELS:
            p_ok = mx["cand"] <= THRESHOLDS["P_vs_triton"] * mx["triton"] and mx["cand"] <= THRESHOLDS["P_vs_hip"] * mx["hip_inst"]
            r_ok = mx["cand_self"] <= THRESHOLDS["R_vs_hip"] * max(mx["hip_self"], 1e-9)
            P_ok &= p_ok; R_ok &= r_ok
            line += f"  cand {mx['cand']:.5f} [{'P ok' if p_ok else 'P FAIL'}]  self: hip {mx['hip_self']:.5f} cand {mx['cand_self']:.6f} [{'R ok' if r_ok else 'R FAIL'}]"
        print(line + ("" if i_ok else "   <-- INSTRUMENT FAIL"), flush=True)
        res["accuracy"][f"{op}_M{M}"] = {k: v for k, v in row.items()}
        save()
verdict["I"] = I_ok
if not I_ok:
    stop("instrument check failed: the reference or the packing is wrong, so no candidate result can be trusted")
if PREFLIGHT:
    print("\nPREFLIGHT PASS: the instrument is sound. Coding may start.")
    res["verdict"] = verdict; save(); sys.exit(0)
verdict["P"], verdict["R"] = P_ok, R_ok

# ---------------------------------------------------------------- S: speed, graphed, distinct copies above the 96 MB cache
def time_body(body, n):
    for _ in range(3):
        body()
    torch.cuda.synchronize()
    gr = torch.cuda.CUDAGraph()
    with torch.cuda.graph(gr):
        body()
    for _ in range(3):
        gr.replay()
    torch.cuda.synchronize()
    s, e = torch.cuda.Event(enable_timing=True), torch.cuda.Event(enable_timing=True)
    t = []
    for _ in range(20):
        s.record(); gr.replay(); e.record(); torch.cuda.synchronize()
        t.append(s.elapsed_time(e) * 1000.0 / n)
    del gr
    return statistics.median(t)

print(f"\n=== speed: us per call, median of 3 shuffled runs", flush=True)
rng = random.Random(777)
res["speed"] = {}
totals = {M: {k: 0.0 for k in KERNELS} for M in MS}
for op, ((K, N), calls) in SHAPES.items():
    per = K * N // 2 + (K // G) * N * 2 + (K // G) * (N // 8) * 4
    n = max(100, -(-401 * 10**6 // per))
    base = make_case(K, N, 1, 5)
    W = {"tri": [tuple(x.clone() for x in base["tri"]) for _ in range(n)],
         "hip": [tuple(x.clone() for x in base["hip"]) for _ in range(n)]}
    for M in MS:
        a = torch.randn(M, K, device=dev, dtype=torch.bfloat16)
        runs = {k: [] for k in KERNELS}
        for _ in range(3):
            order = list(KERNELS); rng.shuffle(order)
            for k in order:
                fn, lay = KERNELS[k]; ws = W[lay]
                def body(fn=fn, ws=ws):
                    for w in ws:
                        fn(a, w)
                runs[k].append(time_body(body, n))
        med = {k: statistics.median(v) for k, v in runs.items()}
        for k in KERNELS:
            totals[M][k] += med[k] * calls / 1000.0
        res["speed"][f"{op}_M{M}"] = runs
        print(f"{op:8s} M{M}  " + "  ".join(f"{k} {med[k]:7.2f}" for k in KERNELS), flush=True)
    del W
    torch.cuda.empty_cache()
    save()
S_ok = True
for M in MS:
    t = totals[M]
    ok = t["cand"] <= t["triton"] - THRESHOLDS["S_margin_ms"]
    S_ok &= ok
    print(f"M{M} per-token ms over 255 calls: triton {t['triton']:.2f}  hip_inst {t['hip_inst']:.2f}  cand {t['cand']:.2f}  "
          f"[{'S ok' if ok else 'S FAIL'}: needs <= {t['triton'] - THRESHOLDS['S_margin_ms']:.2f}]")
res["per_token_ms"] = {str(M): totals[M] for M in MS}
verdict["S"] = S_ok

res["verdict"] = verdict
save()
print("\nVERDICT: " + "  ".join(f"{g} {'PASS' if v else 'FAIL'}" for g, v in verdict.items()))
if all(verdict.values()):
    print("ALL GATES PASS")
    sys.exit(0)
print("NOT PASSED")
sys.exit(1)
