"""attn_gate.py: segment count of the Triton 3D decode attention, at the brain's TP8 per-card shapes. G7 only.

DO NOT EDIT THIS FILE. It prints its own md5; every report must quote it.

  python attn_gate.py --preflight   instrument check only (S = 16, 60K, one sequence). Must pass first.
  python attn_gate.py               full sweep and verdict

Runs the INSTALLED vLLM unified_attention and refuses unless its file is byte-identical to the brain's
(md5 b184d334df3d5f88b782e5b92939d6d0, from the running n02-fp32 container). Mirrors production exactly:
blocks of 400 tokens, K and V interleaved per block as kv_cache.unbind(1) gives them, 3 query heads sharing
1 KV head, head size 256, bf16, paged blocks in shuffled order, 3D threshold 128, segment buffers sized
like triton_attn.py (2 x 128 query tokens), k/v descale as expanded ones, softcap 0.

Cases: context 16K, 60K and 100K; x (1 sequence, 1 query token) = decode, (1 sequence, 2 tokens) = the
speculative verify step the brain now runs, (4 sequences, 1 token) = a small concurrent batch.
Segment counts S: 16 (today), 32, 64, 128 (the kernels need a power of two).

Gates, per case and S:
  ran-3D  the attention launch grid is 3-D with S segments (the path under test really ran)
  I       instrument, S = 16 only: error vs an exact float64 reference <= 0.02 RMS relative,
          and a broken control (the block table pointed at decoy blocks with other contents) >= 0.10
Data: random keys and values plus 8 needle keys per sequence that its queries attend to strongly,
spread across the context so they fall in different segments (attention on real text is peaky;
flat random attention would barely exercise how the kernel combines segments).
  P       precision: error(S) <= 1.25 x error(16) + 1e-6
  R       repeatability: two calls bit-identical
Speed, per case and S: 16 layers per token (16 distinct caches, one CUDA graph), median of 20 replays,
events outside the graph.
Recommendation: among S passing ran-3D, P and R on every case, the lowest summed time over the brain's
working cases (60K, 1 sequence, 1 and 2 tokens), provided it is never more than 3 % slower than S = 16 on
any case, and beats S = 16 on the working cases by at least 3 % (otherwise the answer is: keep 16).
Exit 0 only if the instrument passes and a recommendation exists.
"""
import os, sys, json, math, hashlib, statistics
os.environ["ROCR_VISIBLE_DEVICES"] = "GPU-d580007fa41ec467"
os.environ["HIP_VISIBLE_DEVICES"] = "GPU-d580007fa41ec467"
os.environ["CUDA_VISIBLE_DEVICES"] = "GPU-d580007fa41ec467"
os.environ["HF_HUB_OFFLINE"] = "1"
os.environ["VLLM_PLUGINS"] = ""

HERE = os.path.dirname(os.path.abspath(__file__))
SELF_MD5 = hashlib.md5(open(os.path.abspath(__file__), "rb").read()).hexdigest()
PREFLIGHT = "--preflight" in sys.argv
OUT = os.path.join(HERE, "attn_gate_preflight.json" if PREFLIGHT else "attn_gate_results.json")
BRAIN_KERNEL_MD5 = "b184d334df3d5f88b782e5b92939d6d0"
BRAIN_BACKEND_MD5 = "31f3473a24b53e06327bad0703ba3e8e"

DEV = "cuda"
NQ, NKV, HS, BLOCK = 3, 1, 256, 400          # per card at TP8: 3 query heads share 1 KV head
SEQ_THRESHOLD_3D, BUFDIM = 128, 256           # triton_attn.py: threshold 128, buffers 2 x threshold
LAYERS = 16                                   # full-attention layers per token
CTXS = (16384, 61440, 102400)
CASES = ((1, 1), (1, 2), (4, 1))              # (sequences, query tokens per sequence)
SEGS = (16, 32, 64, 128)
WORKING = [(61440, 1, 1), (61440, 1, 2)]
TH = {"I_err_max": 0.02, "I_broken_min": 0.10, "P_ratio": 1.25, "P_eps": 1e-6, "slower_max": 1.03, "min_gain": 0.97}
res = {"md5": SELF_MD5, "mode": "preflight" if PREFLIGHT else "full", "thresholds": TH}


def log(msg):
    print(msg, flush=True)


def save():
    json.dump(res, open(OUT, "w"), indent=2)


def stop(msg):
    log(f"\nSTOP: {msg}")
    res["stopped"] = msg
    save()
    sys.exit(2)


def cdiv(a, b):
    return (a + b - 1) // b


def rms_rel(x, ref):
    d = x.double() - ref
    return (d.pow(2).mean().sqrt() / ref.pow(2).mean().sqrt()).item()


def build_case(torch, ctx, seqs, ntok, seed, layers=1, decoys=False):
    """Paged caches in production layout, shuffled block order, queries at the last ntok positions.
    decoys=True adds a second set of blocks with other contents, for the broken control."""
    g = torch.Generator(device="cpu").manual_seed(seed)
    L = ctx + ntok
    bps = cdiv(L, BLOCK)
    nblocks = bps * seqs
    total = nblocks * (2 if decoys else 1)
    q = (torch.randn(seqs * ntok, NQ * NKV, HS, generator=g)).to(torch.bfloat16).to(DEV)
    perm = torch.randperm(nblocks, generator=g).to(torch.int32)
    caches = []
    for _ in range(layers):
        kv = torch.randn(total, 2, BLOCK, NKV, HS, generator=g) * 0.5
        for s in range(seqs):                     # 8 needle keys per sequence, spread across its context
            qdir = q[s * ntok: (s + 1) * ntok].float().cpu().sum(dim=(0, 1))
            needle = qdir / qdir.norm() * 16.0
            for j in range(8):
                pos = (2 * j + 1) * ctx // 16
                blk = int(perm[s * bps + pos // BLOCK])
                kv[blk, 0, pos % BLOCK, 0, :] = needle
        caches.append(kv.to(torch.bfloat16).to(DEV))
    block_table = perm.view(seqs, bps).to(DEV)
    cu = torch.arange(0, seqs * ntok + 1, ntok, dtype=torch.int32).to(DEV)
    seq_lens = torch.full((seqs,), L, dtype=torch.int32).to(DEV)
    decoy_table = (block_table + nblocks) if decoys else None
    return {"caches": caches, "block_table": block_table, "decoy_table": decoy_table, "q": q, "cu": cu, "seq_lens": seq_lens,
            "ctx": ctx, "seqs": seqs, "ntok": ntok, "L": L, "bps": bps}


def reference(torch, case):
    """Exact float64 attention per sequence and query position (causal: token i sees keys 0 .. ctx + i)."""
    kv = case["caches"][0]
    scale = 1.0 / math.sqrt(HS)
    outs = []
    for s in range(case["seqs"]):
        blocks = case["block_table"][s].long()
        K = kv[blocks, 0, :, 0, :].reshape(-1, HS)[: case["L"]].double()
        V = kv[blocks, 1, :, 0, :].reshape(-1, HS)[: case["L"]].double()
        for i in range(case["ntok"]):
            qi = case["q"][s * case["ntok"] + i].double()                      # (NQ, HS)
            p = case["ctx"] + i
            w = torch.softmax((qi @ K[: p + 1].T) * scale, dim=-1)
            outs.append(w @ V[: p + 1])
    return torch.stack(outs)


def attention(torch, T, case, S, layer=0, block_table=None, spy=None):
    """One call of the installed unified_attention, exactly as triton_attn.py makes it."""
    kv = case["caches"][layer]
    key_cache, value_cache = kv.unbind(1)
    out = torch.empty_like(case["q"])
    so = torch.empty(BUFDIM, NQ * NKV, S, HS, dtype=torch.float32, device=DEV)
    sm = torch.empty(BUFDIM, NQ * NKV, S, dtype=torch.float32, device=DEV)
    se = torch.empty(BUFDIM, NQ * NKV, S, dtype=torch.float32, device=DEV)
    ones = torch.ones(1, dtype=torch.float32, device=DEV).expand(case["seqs"], NKV)
    T.unified_attention(
        q=case["q"], k=key_cache, v=value_cache, out=out, cu_seqlens_q=case["cu"],
        max_seqlen_q=case["ntok"], seqused_k=case["seq_lens"], max_seqlen_k=case["L"],
        softmax_scale=1.0 / math.sqrt(HS), causal=True, window_size=(-1, -1),
        block_table=case["block_table"] if block_table is None else block_table,
        softcap=0.0, q_descale=None, k_descale=ones, v_descale=ones,
        seq_threshold_3D=SEQ_THRESHOLD_3D, num_par_softmax_segments=S,
        softmax_segm_output=so, softmax_segm_max=sm, softmax_segm_expsum=se)
    return out


def with_grid_spy(T, fn):
    """Run fn while recording the attention kernel's launch grid; always restores the real kernel."""
    orig = T.kernel_unified_attention
    grids = []

    class Spy:
        def __getitem__(self, grid):
            def call(*a, **k):
                grids.append(tuple(grid))
                return orig[grid](*a, **k)
            return call
    T.kernel_unified_attention = Spy()
    try:
        out = fn()
    finally:
        T.kernel_unified_attention = orig
    return out, grids


def time_per_token(torch, T, case, S):
    """16 layers, 16 distinct caches, one CUDA graph; events outside the graph (ROCm forbids them inside)."""
    outs = [None] * LAYERS

    def body():
        for l in range(LAYERS):
            outs[l] = attention(torch, T, case, S, layer=l)
    for _ in range(2):
        body()
    torch.cuda.synchronize()
    g = torch.cuda.CUDAGraph()
    with torch.cuda.graph(g):
        body()
    for _ in range(3):
        g.replay()
    torch.cuda.synchronize()
    e0, e1 = torch.cuda.Event(enable_timing=True), torch.cuda.Event(enable_timing=True)
    t = []
    for _ in range(20):
        e0.record(); g.replay(); e1.record(); torch.cuda.synchronize()
        t.append(e0.elapsed_time(e1))
    del g
    return statistics.median(t)


def main():
    log(f"attn_gate.py md5 {SELF_MD5}  mode {'PREFLIGHT' if PREFLIGHT else 'FULL'}")
    import torch
    import vllm.v1.attention.ops.triton_unified_attention as T
    import vllm.v1.attention.backends.triton_attn as B
    km = hashlib.md5(open(T.__file__, "rb").read()).hexdigest()
    bm = hashlib.md5(open(B.__file__, "rb").read()).hexdigest()
    res["installed"] = {"kernel_md5": km, "backend_md5": bm}
    if km != BRAIN_KERNEL_MD5 or bm != BRAIN_BACKEND_MD5:
        stop(f"installed attention files differ from the brain's (kernel {km}, backend {bm}); results would not apply")
    if torch.cuda.device_count() != 1:
        stop(f"{torch.cuda.device_count()} cards visible, expected exactly G7")
    if torch.cuda.mem_get_info()[0] / 2**30 < 20:
        stop("G7 is not empty")
    log(f"installed attention files match the brain's: kernel {km}, backend {bm}")

    # ---- instrument: S = 16 on the brain's working case, plus the broken control
    ctx0, s0, n0 = WORKING[0]
    c = build_case(torch, ctx0, s0, n0, seed=11, decoys=True)
    ref = reference(torch, c)
    out, grids = with_grid_spy(T, lambda: attention(torch, T, c, 16))
    torch.cuda.synchronize()
    e16 = rms_rel(out, ref)
    e_broken = rms_rel(attention(torch, T, c, 16, block_table=c["decoy_table"]), ref)
    ran = bool(grids) and len(grids[0]) == 3 and grids[0][2] == 16
    i_ok = ran and e16 <= TH["I_err_max"] and e_broken >= TH["I_broken_min"]
    res["instrument"] = {"err_S16": e16, "broken": e_broken, "grid": grids[0] if grids else None, "ok": i_ok}
    save()
    log(f"instrument, 60K decode, S = 16: grid {grids[0] if grids else None} (want (.., 1, 16)), error {e16:.6f} "
        f"(max {TH['I_err_max']}), broken control {e_broken:.3f} (min {TH['I_broken_min']}) -> {'PASS' if i_ok else 'FAIL'}")
    if not i_ok:
        stop("instrument check failed: the reference, the layout or the grid is wrong, so no result can be trusted")
    if PREFLIGHT:
        log("\nPREFLIGHT PASS: the instrument is sound.")
        res["verdict"] = {"I": True}
        save()
        return 0
    c = ref = out = None
    torch.cuda.empty_cache()

    # ---- full sweep
    table = {}
    log(f"\n{'case':22s} {'S':>4s} {'ran-3D':>7s} {'error':>9s} {'vs S16':>7s} {'repeat':>7s} {'ms/token':>9s} {'vs S16':>7s} {'GB/s':>6s}")
    for ctx in CTXS:
        for seqs, ntok in CASES:
            key = f"{ctx // 1024}K s{seqs} q{ntok}"
            c = build_case(torch, ctx, seqs, ntok, seed=100 + ctx // 1024 + seqs * 7 + ntok, layers=LAYERS)
            ref = reference(torch, c)
            rows = {}
            for S in SEGS:
                out, grids = with_grid_spy(T, lambda: attention(torch, T, c, S))
                out2 = attention(torch, T, c, S)
                torch.cuda.synchronize()
                ran = bool(grids) and len(grids[0]) == 3 and grids[0][2] == S
                err = rms_rel(out, ref)
                same = bool(torch.equal(out, out2))
                ms = time_per_token(torch, T, c, S)
                gbps = c["seqs"] * c["L"] * NKV * HS * 2 * 2 * LAYERS / (ms * 1e-3) / 1e9
                rows[S] = {"ran_3d": ran, "grid": grids[0] if grids else None, "err": err, "repeat": same,
                           "ms_per_token": ms, "gbps": gbps}
            base = rows[16]
            for S in SEGS:
                r = rows[S]
                r["err_ratio"] = r["err"] / max(base["err"], 1e-12)
                r["p_ok"] = r["err"] <= TH["P_ratio"] * base["err"] + TH["P_eps"]
                r["speed_vs_16"] = r["ms_per_token"] / base["ms_per_token"]
                log(f"{key:22s} {S:4d} {'yes' if r['ran_3d'] else 'NO':>7s} {r['err']:9.6f} {r['err_ratio']:7.3f} "
                    f"{'yes' if r['repeat'] else 'NO':>7s} {r['ms_per_token']:9.3f} {r['speed_vs_16']:7.3f} {r['gbps']:6.0f}")
            table[key] = {"ctx": ctx, "seqs": seqs, "ntok": ntok, "rows": {str(S): v for S, v in rows.items()}}
            res["table"] = table
            save()
            c = ref = None
            torch.cuda.empty_cache()

    # ---- recommendation
    eligible = []
    for S in SEGS:
        ok = all(t["rows"][str(S)]["ran_3d"] and t["rows"][str(S)]["p_ok"] and t["rows"][str(S)]["repeat"]
                 and t["rows"][str(S)]["speed_vs_16"] <= TH["slower_max"] for t in table.values())
        if ok:
            work = sum(table[f"{ctx // 1024}K s{s} q{n}"]["rows"][str(S)]["ms_per_token"] for ctx, s, n in WORKING)
            eligible.append((work, S))
    base_work = sum(table[f"{ctx // 1024}K s{s} q{n}"]["rows"]["16"]["ms_per_token"] for ctx, s, n in WORKING)
    if not eligible:
        res["verdict"] = {"I": True, "recommendation": None}
        save()
        log("\nNO RECOMMENDATION: no segment count passed ran-3D, P and R on every case without slowing any case by more than 3 %.")
        return 1
    work, best = min(eligible)
    if best != 16 and work > TH["min_gain"] * base_work:
        work, best = base_work, 16      # a gain under 3 % is noise, not a reason to change the brain
    res["verdict"] = {"I": True, "recommendation": best, "working_ms_S16": base_work, "working_ms_best": work}
    save()
    log(f"\nRECOMMENDATION: S = {best}. Brain's working cases (60K decode + 60K verify): {base_work:.3f} ms at S = 16, "
        f"{work:.3f} ms at S = {best} (per token, 16 layers each).")
    log("ALL GATES PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
